// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Success() {
    // Test name: success 
    // Step # | name | target | value
    // 1 | open | /SignIn | 
    driver.Navigate().GoToUrl("https://localhost:7272/SignIn");
    // 2 | setWindowSize | 550x692 | 
    driver.Manage().Window.Size = new System.Drawing.Size(550, 692);
    // 3 | click | id=email | 
    driver.FindElement(By.Id("email")).Click();
    // 4 | click | id=email | 
    driver.FindElement(By.Id("email")).Click();
    // 5 | doubleClick | id=email | 
    {
      var element = driver.FindElement(By.Id("email"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    // 6 | click | linkText=Create an account | 
    driver.FindElement(By.LinkText("Create an account")).Click();
    // 7 | click | css=form:nth-child(1) > button | 
    driver.FindElement(By.CssSelector("form:nth-child(1) > button")).Click();
    // 8 | click | id=fname | 
    driver.FindElement(By.Id("fname")).Click();
    // 9 | type | id=fname | sadsdaa
    driver.FindElement(By.Id("fname")).SendKeys("sadsdaa");
    // 10 | click | id=lname | 
    driver.FindElement(By.Id("lname")).Click();
    // 11 | type | id=lname | bnmk
    driver.FindElement(By.Id("lname")).SendKeys("bnmk");
    // 12 | click | id=email | 
    driver.FindElement(By.Id("email")).Click();
    // 13 | type | id=email | uuuuuu
    driver.FindElement(By.Id("email")).SendKeys("uuuuuu");
    // 14 | sendKeys | id=email | ${KEY_UP}
    driver.FindElement(By.Id("email")).SendKeys(Keys.Up);
    // 15 | type | id=email | aaaaa@uuuuuu.com
    driver.FindElement(By.Id("email")).SendKeys("aaaaa@uuuuuu.com");
    // 16 | click | id=password | 
    driver.FindElement(By.Id("password")).Click();
    // 17 | type | id=password | 1w23
    driver.FindElement(By.Id("password")).SendKeys("1w23");
    // 18 | click | id=passdup | 
    driver.FindElement(By.Id("passdup")).Click();
    // 19 | type | id=passdup | 1w23
    driver.FindElement(By.Id("passdup")).SendKeys("1w23");
    // 20 | click | css=button | 
    driver.FindElement(By.CssSelector("button")).Click();
  }
}
